export const populationDataMale = {
    "2000": [
        { "name": "Ang Mo Kio", "value": 89800 },
        { "name": "Bedok", "value": 141350 },
        { "name": "Bishan", "value": 44460 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 63800 },
        { "name": "Bukit Merah", "value": 74400 },
        { "name": "Bukit Panjang", "value": 48700 },
        { "name": "Bukit Timah", "value": 30570 },
       
    ],
    "2001": [
        { "name": "Ang Mo Kio", "value": 87460 },
        { "name": "Bedok", "value": 141040 },
        { "name": "Bishan", "value": 43990 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 63830 },
        { "name": "Bukit Merah", "value": 72610 },
        { "name": "Bukit Panjang", "value": 53990 },
        { "name": "Bukit Timah", "value": 31250 },
        
    ],
    "2002": [
        { "name": "Ang Mo Kio", "value": 85850 },
        { "name": "Bedok", "value": 141310 },
        { "name": "Bishan", "value": 43590 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 64920 },
        { "name": "Bukit Merah", "value": 72170 },
        { "name": "Bukit Panjang", "value": 56440 },
        { "name": "Bukit Timah", "value": 31620 },

    ],
    "2003": [
        { "name": "Ang Mo Kio", "value": 83800 },
        { "name": "Bedok", "value": 137970 },
        { "name": "Bishan", "value": 42170 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 65160 },
        { "name": "Bukit Merah", "value": 69990 },
        { "name": "Bukit Panjang", "value": 57520 },
        { "name": "Bukit Timah", "value": 30470 },
       
    ],
    "2004": [
        { "name": "Ang Mo Kio", "value": 83150 },
        { "name": "Bedok", "value": 137760 },
        { "name": "Bishan", "value": 42570 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 66400 },
        { "name": "Bukit Merah", "value": 70080 },
        { "name": "Bukit Panjang", "value": 59190 },
        { "name": "Bukit Timah", "value": 31200 },
        
    ],
    "2005": [
        { "name": "Ang Mo Kio", "value": 83280 },
        { "name": "Bedok", "value": 138230 },
        { "name": "Bishan", "value": 43070 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 67610 },
        { "name": "Bukit Merah", "value": 70640 },
        { "name": "Bukit Panjang", "value": 60100 },
        { "name": "Bukit Timah", "value": 32040 },
       
    ],
    "2006": [
        { "name": "Ang Mo Kio", "value": 83780 },
        { "name": "Bedok", "value": 138810 },
        { "name": "Bishan", "value": 43590 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 68980 },
        { "name": "Bukit Merah", "value": 72110 },
        { "name": "Bukit Panjang", "value": 60700 },
        { "name": "Bukit Timah", "value": 33080 },
        
    ],
    "2007": [
        { "name": "Ang Mo Kio", "value": 84550 },
        { "name": "Bedok", "value": 140020 },
        { "name": "Bishan", "value": 43900 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 69850 },
        { "name": "Bukit Merah", "value": 73660 },
        { "name": "Bukit Panjang", "value": 61450 },
        { "name": "Bukit Timah", "value": 33680 },
       
    ],
    "2008": [
        { "name": "Ang Mo Kio", "value": 85500 },
        { "name": "Bedok", "value": 140630 },
        { "name": "Bishan", "value": 44150 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 70230 },
        { "name": "Bukit Merah", "value": 74990 },
        { "name": "Bukit Panjang", "value": 62410 },
        { "name": "Bukit Timah", "value": 32780 },
       
    ],
    "2009": [
        { "name": "Ang Mo Kio", "value": 87130 },
        { "name": "Bedok", "value": 143400 },
        { "name": "Bishan", "value": 44360 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 71510 },
        { "name": "Bukit Merah", "value": 76630 },
        { "name": "Bukit Panjang", "value": 63690 },
        { "name": "Bukit Timah", "value": 32570 },
        
    ],
    "2010": [
        { "name": "Ang Mo Kio", "value": 87110 },
        { "name": "Bedok", "value": 144400 },
        { "name": "Bishan", "value": 44530 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 71360 },
        { "name": "Bukit Merah", "value": 76750 },
        { "name": "Bukit Panjang", "value": 64230 },
        { "name": "Bukit Timah", "value": 32980 },
       
    ],
    "2011": [
        { "name": "Ang Mo Kio", "value": 86650 },
        { "name": "Bedok", "value": 144720 },
        { "name": "Bishan", "value": 44160 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 70840 },
        { "name": "Bukit Merah", "value": 76220 },
        { "name": "Bukit Panjang", "value": 64540 },
        { "name": "Bukit Timah", "value": 33020 },
       
    ],
    "2012": [
        { "name": "Ang Mo Kio", "value": 86610 },
        { "name": "Bedok", "value": 144420 },
        { "name": "Bishan", "value": 45110 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 70330 },
        { "name": "Bukit Merah", "value": 76560 },
        { "name": "Bukit Panjang", "value": 65280 },
        { "name": "Bukit Timah", "value": 33560 },
       
    ],
    "2013": [
        { "name": "Ang Mo Kio", "value": 86480 },
        { "name": "Bedok", "value": 143670 },
        { "name": "Bishan", "value": 45210 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 70240 },
        { "name": "Bukit Merah", "value": 75780 },
        { "name": "Bukit Panjang", "value": 65500 },
        { "name": "Bukit Timah", "value": 34060 },
       
    ],
    "2014": [
        { "name": "Ang Mo Kio", "value": 86080 },
        { "name": "Bedok", "value": 143120 },
        { "name": "Bishan", "value": 44730 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 69760 },
        { "name": "Bukit Merah", "value": 75940 },
        { "name": "Bukit Panjang", "value": 66250 },
        { "name": "Bukit Timah", "value": 34330 },
        
    ],
    "2015": [
        { "name": "Ang Mo Kio", "value": 84220 },
        { "name": "Bedok", "value": 141220 },
        { "name": "Bishan", "value": 44110 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 68650 },
        { "name": "Bukit Merah", "value": 75450 },
        { "name": "Bukit Panjang", "value": 69160 },
        { "name": "Bukit Timah", "value": 34660 },
        
    ],
    "2016": [
        { "name": "Ang Mo Kio", "value": 82140 },
        { "name": "Bedok", "value": 139730 },
        { "name": "Bishan", "value": 43770 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 67960 },
        { "name": "Bukit Merah", "value": 74620 },
        { "name": "Bukit Panjang", "value": 70160 },
        { "name": "Bukit Timah", "value": 35140 },
       
    ],
    "2017": [
        { "name": "Ang Mo Kio", "value": 80040 },
        { "name": "Bedok", "value": 138460 },
        { "name": "Bishan", "value": 43850 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 67930 },
        { "name": "Bukit Merah", "value": 73630 },
        { "name": "Bukit Panjang", "value": 70340 },
        { "name": "Bukit Timah", "value": 35470 },
        
    ],
    "2018": [
        { "name": "Ang Mo Kio", "value": 79360 },
        { "name": "Bedok", "value": 136520 },
        { "name": "Bishan", "value": 42900 },
        { "name": "Boon Lay", "value": 0 },
        { "name": "Bukit Batok", "value": 70860 },
        { "name": "Bukit Merah", "value": 73120 },
        { "name": "Bukit Panjang", "value": 69540 },
        { "name": "Bukit Timah", "value": 35830 },
        
    ]
};